//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectClg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Updates = new HashSet<Update>();
        }
    
        public string StudentName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string RollNumber { get; set; }
        public string Section { get; set; }
        public string Email { get; set; }
        public long PhoneNumber { get; set; }
        public Nullable<int> AddressCode { get; set; }
        public double StudentFee { get; set; }
        public string Username { get; set; }
        public string StudentPassword { get; set; }
        public string CreatedAdmin { get; set; }
        public string CreatedTeacher { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Update> Updates { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
