//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectClg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Students = new HashSet<Student>();
            this.Updates = new HashSet<Update>();
        }
    
        public string TeacherName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string EmployeeId { get; set; }
        public string Email { get; set; }
        public long PhoneNumber { get; set; }
        public Nullable<int> AddressCode { get; set; }
        public string Username { get; set; }
        public string TeacherPassword { get; set; }
        public string Createdby { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Update> Updates { get; set; }
    }
}
