//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectClg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update
    {
        public int UpdatesId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Information { get; set; }
        public string CreatedAdmin { get; set; }
        public string CreatedTeacher { get; set; }
        public string CreatedStudent { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
